version: '3.8'

services:
  ib-gateway:
    build:
      context: ./ib-gateway
      dockerfile: Dockerfile.ib-gateway
    env_file: .env
    ports:
      - "127.0.0.1:4002:4004"

  dyn_opt_container:
    build:
      context: ./risk_management
      dockerfile: docker/Dockerfile.dyn_opt
    ports:
      - "5000:5000"

  risk_measures_container:
    build:
      context: ./risk_management
      dockerfile: docker/Dockerfile.risk_measures
    ports:
      - "5001:5001"
